# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgresql:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=secret123
spring.datasource.driver-class-name=org.pget ostgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# JWT ? store secret in env variable in real production!
jwt.secret=YourSuperSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm!
jwt.access-secret=AccessTokenSecretKeyThatIsAtLeast256BitsLongForSecurity!
jwt.refresh-secret=RefreshTokenSecretKeyDifferentFromAccessKeyForSecurity!
jwt.expiration=86400000
# 86400000ms = 24 hours

# Allow Next.js origin
cors.allowed-origin=http://frontend-edhaya-anbalagan-dev.apps.rm1.0a51.p1.openshiftapps.com

#HikariCP
spring.datasource.hikari.initializationFailTimeout=60000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.validationTimeout=5000
spring.datasource.hikari.maximumPoolSize=5