# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgresql:5432/authdb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# JWT - secrets are provided via environment variables injected from Kubernetes Secrets
jwt.secret=${JWT_SECRET}
jwt.access-secret=${JWT_ACCESS_SECRET}
jwt.refresh-secret=${JWT_REFRESH_SECRET}
jwt.expiration=86400000
# 86400000ms = 24 hours

# Allow Next.js origin
cors.allowed-origin=http://frontend-edhaya-anbalagan-dev.apps.rm1.0a51.p1.openshiftapps.com

#HikariCP
spring.datasource.hikari.initializationFailTimeout=60000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.validationTimeout=5000
spring.datasource.hikari.maximumPoolSize=5

#Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
