# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=secret123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT ? store secret in env variable in real production!
jwt.secret=YourSuperSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm!
jwt.access-secret=AccessTokenSecretKeyThatIsAtLeast256BitsLongForSecurity!
jwt.refresh-secret=RefreshTokenSecretKeyDifferentFromAccessKeyForSecurity!
jwt.expiration=86400000
# 86400000ms = 24 hours

# Allow Next.js origin
cors.allowed-origin=http://localhost:3000