apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    app: backend
type: Opaque
stringData:
  # The following values are dummy examples. 
  # In a real environment, you should replace these with actual secrets or use a sealed secret mechanism.
  JWT_SECRET: "YourSuperSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm!"
  JWT_ACCESS_SECRET: "AccessTokenSecretKeyThatIsAtLeast256BitsLongForSecurity!"
  JWT_REFRESH_SECRET: "RefreshTokenSecretKeyDifferentFromAccessKeyForSecurity!"
