# Headless service — gives stable DNS to each pod (kafka-0, kafka-1, kafka-2, kafka-3, kafka-4)
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: edhaya-anbalagan-dev
spec:
  clusterIP: None       # headless
  selector:
    app: kafka
  ports:
    - name: broker
      port: 9092
    - name: controller
      port: 9093
---
# Client service — for your Spring Boot app to connect
apiVersion: v1
kind: Service
metadata:
  name: kafka-client
  namespace: edhaya-anbalagan-dev
spec:
  selector:
    app: kafka
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: edhaya-anbalagan-dev
spec:
  serviceName: kafka       # must match headless service name
  replicas: 5
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: public.ecr.aws/bitnami/kafka:3.6.0   # Bypasses Docker Hub pull limit
          command:
            - /bin/bash
            - -c
            - |
              # Extract pod index to use as KAFKA_CFG_NODE_ID (e.g. kafka-0 -> 0)
              export KAFKA_CFG_NODE_ID=$(echo $HOSTNAME | grep -o -E '[0-9]+$')
              # Set advertised listeners dynamically using the pod's DNS name
              export KAFKA_CFG_ADVERTISED_LISTENERS="PLAINTEXT://${HOSTNAME}.kafka.edhaya-anbalagan-dev.svc.cluster.local:9092"
              /opt/bitnami/scripts/kafka/entrypoint.sh /opt/bitnami/scripts/kafka/run.sh
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            # KRaft mode — no ZooKeeper
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"

            # All 5 brokers listed — kafka-0, kafka-1, kafka-2, kafka-3, kafka-4
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "0@kafka-0.kafka:9093,1@kafka-1.kafka:9093,2@kafka-2.kafka:9093,3@kafka-3.kafka:9093,4@kafka-4.kafka:9093"
            
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_KRAFT_CLUSTER_ID
              value: "4L62xdtTRt2RPMw3s3tzzg"

          # Storage per broker
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka

  # Each broker gets its own PVC automatically
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
