apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql

  template:
    metadata:
      labels:
        app: postgresql

    spec:
      containers:
        - name: postgresql

          image: quay.io/sclorg/postgresql-15-c9s

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRESQL_USER
              value: postgres

            - name: POSTGRESQL_PASSWORD
              value: secret123

            - name: POSTGRESQL_DATABASE
              value: authdb

          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: postgres-storage

      volumes:
        - name: postgres-storage
          emptyDir: {}