apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgresql

  template:
    metadata:
      labels:
        app: postgresql

    spec:
      securityContext:
        fsGroup: 26

      containers:
        - name: postgresql

          image: quay.io/sclorg/postgresql-15-c9s

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: authdb

            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              value: secret123

            # IMPORTANT
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
