name: Deploy to OpenShift

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------
      # Backend Build
      # -------------------

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build backend
        working-directory: mywebsite-backend
        run: mvn clean package -DskipTests

      # -------------------
      # Frontend Build
      # -------------------

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build frontend
        working-directory: mywebsite-frontend
        run: |
          npm install
          npm run build

      # -------------------
      # Login GHCR
      # -------------------

      - name: Set repository owner to lowercase
        run: echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # -------------------
      # Build Backend Image
      # -------------------

      - name: Build backend image
        run: |
          docker build -t ghcr.io/${{ env.REPO_OWNER }}/mywebsite-backend:${{ github.sha }} ./mywebsite-backend

      - name: Push backend image
        run: |
          docker push ghcr.io/${{ env.REPO_OWNER }}/mywebsite-backend:${{ github.sha }}

      # -------------------
      # Build Frontend Image
      # -------------------

      - name: Build frontend image
        run: |
          docker build --build-arg NEXT_PUBLIC_API_URL=http://backend-${{ secrets.OPENSHIFT_NAMESPACE }}.apps.rm1.0a51.p1.openshiftapps.com -t ghcr.io/${{ env.REPO_OWNER }}/mywebsite-frontend:${{ github.sha }} ./mywebsite-frontend

      - name: Push frontend image
        run: |
          docker push ghcr.io/${{ env.REPO_OWNER }}/mywebsite-frontend:${{ github.sha }}

      # -------------------
      # Login OpenShift
      # -------------------

      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin

      - name: Login to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      # -------------------
      # Deploy K8s
      # -------------------

      - name: Update Kubernetes manifests
        run: |
          sed -i "s|ghcr.io/IMAGE_OWNER/mywebsite-backend:IMAGE_TAG|ghcr.io/${{ env.REPO_OWNER }}/mywebsite-backend:${{ github.sha }}|g" k8s/backend/backend-deployment.yaml
          sed -i "s|ghcr.io/IMAGE_OWNER/mywebsite-frontend:IMAGE_TAG|ghcr.io/${{ env.REPO_OWNER }}/mywebsite-frontend:${{ github.sha }}|g" k8s/frontend/frontend-deployment.yaml

      - name: Apply Kubernetes manifests
        run: oc apply -R -f k8s/